<!--#include file="dn_fun_comunes.asp"--><!--#include file="dn_auten.inc"--><!--#include file="adovbs.inc"--><!--#include file="dn_conexion.asp"--><%'Permite auditar las acciones%><!--#include file="spl_auditoria.inc.asp"--><%if request.form("idcheck")="" then	flashMsgCreate "No se indicó ninguna sustancia que eliminar.", "Advertencia"else	ids=request.form("idcheck")		'consultamos que archivos hay que borrar	set rstb=objconn1.execute("select estructura_molecular from  dn_risc_sustancias where id IN (" &ids& ")")	do while not rstb.eof		estructura_molecular=rstb("estructura_molecular")		if estructura_molecular<>"" then borrarfichero "\estructuras\" &estructura_molecular	rstb.movenext	loop	rstb.close	set rstb=nothing		objconn1.execute("delete from dn_risc_sustancias where id IN (" &ids& ")")	objconn1.execute("delete from dn_risc_sustancias_ambiente where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_cancer_otras where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_iarc where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_mama_cop where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_neuro_disruptor where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_ambiente where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_vl where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_salud where id_sustancia IN (" &ids& ")")

	objconn1.execute("delete from dn_risc_sinonimos where id_sustancia IN (" &ids& ")")	objconn1.execute("delete from dn_risc_nombres_comerciales where id_sustancia IN (" &ids& ")")			objconn1.execute("delete from dn_risc_sustancias_por_grupos where id_sustancia IN (" &ids& ")")		objconn1.execute("delete from dn_risc_sustancias_por_usos where id_sustancia IN (" &ids& ")")		objconn1.execute("delete from dn_risc_sustancias_por_enfermedades where id_sustancia IN (" &ids& ")")		objconn1.execute("delete from dn_risc_sustancias_por_companias where id_sustancia IN (" &ids& ")")
	objconn1.execute("delete from dn_risc_sustancias_por_sectores where id_sustancia IN (" &ids& ")")			objconn1.execute("delete from dn_alter_ficheros_por_sustancias where id_sustancia IN (" &ids& ")")			flashMsgCreate "Las sustancias seleccionadas han sido eliminadas.", "OK"end if' ** AUDITORIA **call auditaYCierraConexion("eliminar","sustancia(s)",ids)response.redirect "dn_sustancias.asp"'flashMsgShow()%>
